### PR TITLE
#192: Cyclical dependencies

### PR DESCRIPTION
**Pull request by laryn**

### CODE REVIEW

**Review by EganSolo — COMMENTED** [review]
I think this looks good. I'll want to test it first. Is there a way to dl this version?

**Comment by EganSolo** [comment]
Hey Laryn,
I managed to enable ubercart, store and product. The instal process bombs on orders: 
Fatal error: Class 'EMWController' not found in /var/backdrop_fresh_install/modules/ubercart-1.x-1.x/uc_order/uc_order.controller.inc on line 65

After sniffing around this site, I figured that EMWController is declared in the deprecated entity_metadata_wrapper module. I replaced the offending lines in uc_order and uc_cart with "extends EntityPlusController" and that did it.

Should I signal that as a separate bug?

**Comment by laryn** [comment]
@EganSolo I think you pinpointed the same thing I did. I just looked at this issue again:
https://github.com/backdrop-contrib/ubercart/issues/167

And I realize I never submitted a formal PR. Do you want to submit a PR there with those changes? Maybe you can also make the Rules dependency to be `>= 1.x-2.1.0` to make sure it only installs the next version on the version of Rules that uses Entity Plus instead of Entity Metadata Wrapper.

**Comment by EganSolo** [comment]
Hi Laryn,

I'm still _very_ new to the Git hub system (as in I haven't used it
before). I would let you do the update if you don't mind, but I'm happy to
be a tester for now and help fix bugs. Once I'm more comfortable with Git
and Backdrop, I'll take a more active role.

I test on local ubuntu in VM and I can whip-up a new Backdrop env very
quickly for testing purposes. I'm not certain I understand when you're done
merging code so I can test it. I would expect to see somewhere on the Git
site a link to "newer code" indicating the fixes. I'm sure it's there. If
you could point me in the right direction that would be very helpful.

Egan.

**Pull request merged**
